# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='news/images')),
                ('short_description', models.TextField(max_length=300)),
                ('publication_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
