# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160328_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_slide_on_save',
            field=models.BooleanField(default=False),
        ),
    ]
