# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_create_slide_on_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Author', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
