# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160526_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='heading',
            new_name='title',
        ),
    ]
