# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160903_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Attentor',
        ),
        migrations.RenameModel(
            old_name='AdvertisementContentImage',
            new_name='AttentorContentImage',
        ),
        migrations.RenameField(
            model_name='attentorcontentimage',
            old_name='advertisement',
            new_name='attentor',
        ),
    ]
