# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(null=True, upload_to='advertisement/images'),
        ),
    ]
