# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='author',
            field=models.CharField(default='Анонім', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement/images'),
        ),
    ]
