# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160526_2150'),
        ('advertisement', '0003_auto_20160801_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='tag',
            field=models.ManyToManyField(to='news.Tag'),
        ),
    ]
