# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('number', models.SmallIntegerField(default=-1)),
                ('is_percentage', models.BooleanField(default=False)),
            ],
        ),
    ]
