# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FactArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='is_percentage',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='number',
        ),
        migrations.AddField(
            model_name='factargument',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact.Fact'),
        ),
        migrations.AddField(
            model_name='factargument',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact.ArgumentType'),
        ),
    ]
