# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('logotype', models.ImageField(upload_to='technology/images')),
            ],
            options={
                'verbose_name_plural': 'technologies',
            },
        ),
    ]
