# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_priority', models.SmallIntegerField(auto_created=True, unique=True)),
                ('big_slogan', models.CharField(max_length=200)),
                ('small_slogan', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='department/images/slider')),
                ('action_href', models.CharField(max_length=200)),
            ],
        ),
    ]
