# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='display_priority',
            field=models.SmallIntegerField(),
        ),
    ]
