# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('logotype', models.ImageField(upload_to='')),
                ('site_url', models.URLField()),
            ],
        ),
    ]
