# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logotype',
            field=models.ImageField(upload_to='partner/images'),
        ),
    ]
